/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed7;
  GtkWidget *entry_mat_n;
  GtkWidget *button_aff;
  GtkWidget *label6;
  GtkWidget *label_aff;
  GtkWidget *label5;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("AFFICHE DE NOMBRE D'UN TYPE"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window2), fixed7);

  entry_mat_n = gtk_entry_new ();
  gtk_widget_show (entry_mat_n);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_mat_n, 144, 24);
  gtk_widget_set_size_request (entry_mat_n, 166, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mat_n), 8226);

  button_aff = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_aff);
  gtk_fixed_put (GTK_FIXED (fixed7), button_aff, 168, 128);
  gtk_widget_set_size_request (button_aff, 86, 32);

  label6 = gtk_label_new (_("Nombre ="));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed7), label6, 32, 208);
  gtk_widget_set_size_request (label6, 88, 32);

  label_aff = gtk_label_new ("");
  gtk_widget_show (label_aff);
  gtk_fixed_put (GTK_FIXED (fixed7), label_aff, 168, 200);
  gtk_widget_set_size_request (label_aff, 112, 48);

  label5 = gtk_label_new (_("Type \303\240 Afficher"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed7), label5, 32, 24);
  gtk_widget_set_size_request (label5, 105, 32);

  g_signal_connect ((gpointer) button_aff, "clicked",
                    G_CALLBACK (on_button_aff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, entry_mat_n, "entry_mat_n");
  GLADE_HOOKUP_OBJECT (window2, button_aff, "button_aff");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, label_aff, "label_aff");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");

  return window2;
}

